NIFTY500_MAP = {
    '360 one wam ltd': '360ONE.NS',
    '3m india ltd': '3MINDIA.NS',
    'abb india ltd': 'ABB.NS',
    'acc ltd': 'ACC.NS',
    'aia engineering ltd': 'AIAENG.NS',
    'apl apollo tubes ltd': 'APLAPOLLO.NS',
    'au small finance bank ltd': 'AUBANK.NS',
    'aarti industries ltd': 'AARTIIND.NS',
    'aavas financiers ltd': 'AAVAS.NS',
    'abbott india ltd': 'ABBOTINDIA.NS',
    'action construction equipment ltd': 'ACE.NS',
    'adani energy solutions ltd': 'ADANIENSOL.NS',
    'adani enterprises ltd': 'ADANIENT.NS',
    'adani green energy ltd': 'ADANIGREEN.NS',
    'adani ports and special economic zone ltd': 'ADANIPORTS.NS',
    'adani power ltd': 'ADANIPOWER.NS',
    'adani total gas ltd': 'ATGL.NS',
    'adani wilmar ltd': 'AWL.NS',
    'aditya birla capital ltd': 'ABCAPITAL.NS',
    'aditya birla fashion and retail ltd': 'ABFRL.NS',
    'aegis logistics ltd': 'AEGISLOG.NS',
    'aether industries ltd': 'AETHER.NS',
    'affle india ltd': 'AFFLE.NS',
    'ajanta pharmaceuticals ltd': 'AJANTPHARM.NS',
    'alembic pharmaceuticals ltd': 'APLLTD.NS',
    'alkem laboratories ltd': 'ALKEM.NS',
    'alkyl amines chemicals ltd': 'ALKYLAMINE.NS',
    'allcargo logistics ltd': 'ALLCARGO.NS',
    'alok industries ltd': 'ALOKINDS.NS',
    'amara raja energy mobility ltd': 'ARE&M.NS',
    'amber enterprises india ltd': 'AMBER.NS',
    'ambuja cements ltd': 'AMBUJACEM.NS',
    'anand rathi wealth ltd': 'ANANDRATHI.NS',
    'angel one ltd': 'ANGELONE.NS',
    'anupam rasayan india ltd': 'ANURAS.NS',
    'apar industries ltd': 'APARINDS.NS',
    'apollo hospitals enterprise ltd': 'APOLLOHOSP.NS',
    'apollo tyres ltd': 'APOLLOTYRE.NS',
    'aptus value housing finance india ltd': 'APTUS.NS',
    'archean chemical industries ltd': 'ACI.NS',
    'asahi india glass ltd': 'ASAHIINDIA.NS',
    'ashok leyland ltd': 'ASHOKLEY.NS',
    'asian paints ltd': 'ASIANPAINT.NS',
    'aster dm healthcare ltd': 'ASTERDM.NS',
    'astrazeneca pharma india ltd': 'ASTRAZEN.NS',
    'astral ltd': 'ASTRAL.NS',
    'atul ltd': 'ATUL.NS',
    'aurobindo pharma ltd': 'AUROPHARMA.NS',
    'avanti feeds ltd': 'AVANTIFEED.NS',
    'avenue supermarts ltd': 'DMART.NS',
    'axis bank ltd': 'AXISBANK.NS',
    'beml ltd': 'BEML.NS',
    'bls international services ltd': 'BLS.NS',
    'bse ltd': 'BSE.NS',
    'bajaj auto ltd': 'BAJAJ-AUTO.NS',
    'bajaj finance ltd': 'BAJFINANCE.NS',
    'bajaj finserv ltd': 'BAJAJFINSV.NS',
    'bajaj holdings investment ltd': 'BAJAJHLDNG.NS',
    'balaji amines ltd': 'BALAMINES.NS',
    'balkrishna industries ltd': 'BALKRISIND.NS',
    'balrampur chini mills ltd': 'BALRAMCHIN.NS',
    'bandhan bank ltd': 'BANDHANBNK.NS',
    'bank of baroda': 'BANKBARODA.NS',
    'bank of india': 'BANKINDIA.NS',
    'bank of maharashtra': 'MAHABANK.NS',
    'bata india ltd': 'BATAINDIA.NS',
    'bayer cropscience ltd': 'BAYERCROP.NS',
    'berger paints india ltd': 'BERGEPAINT.NS',
    'bharat dynamics ltd': 'BDL.NS',
    'bharat electronics ltd': 'BEL.NS',
    'bharat forge ltd': 'BHARATFORG.NS',
    'bharat heavy electricals ltd': 'BHEL.NS',
    'bharat petroleum corporation ltd': 'BPCL.NS',
    'bharti airtel ltd': 'BHARTIARTL.NS',
    'bikaji foods international ltd': 'BIKAJI.NS',
    'biocon ltd': 'BIOCON.NS',
    'birla corporation ltd': 'BIRLACORPN.NS',
    'birlasoft ltd': 'BSOFT.NS',
    'blue dart express ltd': 'BLUEDART.NS',
    'blue star ltd': 'BLUESTARCO.NS',
    'bombay burmah trading corporation ltd': 'BBTC.NS',
    'borosil renewables ltd': 'BORORENEW.NS',
    'bosch ltd': 'BOSCHLTD.NS',
    'brigade enterprises ltd': 'BRIGADE.NS',
    'britannia industries ltd': 'BRITANNIA.NS',
    'c e info systems ltd': 'MAPMYINDIA.NS',
    'ccl products i ltd': 'CCL.NS',
    'cesc ltd': 'CESC.NS',
    'cg power and industrial solutions ltd': 'CGPOWER.NS',
    'cie automotive india ltd': 'CIEINDIA.NS',
    'crisil ltd': 'CRISIL.NS',
    'csb bank ltd': 'CSBBANK.NS',
    'campus activewear ltd': 'CAMPUS.NS',
    'can fin homes ltd': 'CANFINHOME.NS',
    'canara bank': 'CANBK.NS',
    'caplin point laboratories ltd': 'CAPLIPOINT.NS',
    'capri global capital ltd': 'CGCL.NS',
    'carborundum universal ltd': 'CARBORUNIV.NS',
    'castrol india ltd': 'CASTROLIND.NS',
    'ceat ltd': 'CEATLTD.NS',
    'cello world ltd': 'CELLO.NS',
    'central bank of india': 'CENTRALBK.NS',
    'central depository services india ltd': 'CDSL.NS',
    'century plyboards india ltd': 'CENTURYPLY.NS',
    'aditya birla real estate ltd': 'ABREL.NS',
    'cera sanitaryware ltd': 'CERA.NS',
    'chalet hotels ltd': 'CHALET.NS',
    'chambal fertilizers chemicals ltd': 'CHAMBLFERT.NS',
    'chemplast sanmar ltd': 'CHEMPLASTS.NS',
    'chennai petroleum corporation ltd': 'CHENNPETRO.NS',
    'cholamandalam financial holdings ltd': 'CHOLAHLDNG.NS',
    'cholamandalam investment and finance company ltd': 'CHOLAFIN.NS',
    'cipla ltd': 'CIPLA.NS',
    'city union bank ltd': 'CUB.NS',
    'clean science and technology ltd': 'CLEAN.NS',
    'coal india ltd': 'COALINDIA.NS',
    'cochin shipyard ltd': 'COCHINSHIP.NS',
    'coforge ltd': 'COFORGE.NS',
    'colgate palmolive india ltd': 'COLPAL.NS',
    'computer age management services ltd': 'CAMS.NS',
    'concord biotech ltd': 'CONCORDBIO.NS',
    'container corporation of india ltd': 'CONCOR.NS',
    'coromandel international ltd': 'COROMANDEL.NS',
    'craftsman automation ltd': 'CRAFTSMAN.NS',
    'creditaccess grameen ltd': 'CREDITACC.NS',
    'crompton greaves consumer electricals ltd': 'CROMPTON.NS',
    'cummins india ltd': 'CUMMINSIND.NS',
    'cyient ltd': 'CYIENT.NS',
    'dcm shriram ltd': 'DCMSHRIRAM.NS',
    'dlf ltd': 'DLF.NS',
    'doms industries ltd': 'DOMS.NS',
    'dabur india ltd': 'DABUR.NS',
    'dalmia bharat ltd': 'DALBHARAT.NS',
    'data patterns india ltd': 'DATAPATTNS.NS',
    'deepak fertilisers petrochemicals corp ltd': 'DEEPAKFERT.NS',
    'deepak nitrite ltd': 'DEEPAKNTR.NS',
    'delhivery ltd': 'DELHIVERY.NS',
    'devyani international ltd': 'DEVYANI.NS',
    'divi s laboratories ltd': 'DIVISLAB.NS',
    'dixon technologies india ltd': 'DIXON.NS',
    'dr lal path labs ltd': 'LALPATHLAB.NS',
    'dr reddy s laboratories ltd': 'DRREDDY.NS',
    'e i d parry india ltd': 'EIDPARRY.NS',
    'eih ltd': 'EIHOTEL.NS',
    'epl ltd': 'EPL.NS',
    'easy trip planners ltd': 'EASEMYTRIP.NS',
    'eicher motors ltd': 'EICHERMOT.NS',
    'elecon engineering co ltd': 'ELECON.NS',
    'elgi equipments ltd': 'ELGIEQUIP.NS',
    'emami ltd': 'EMAMILTD.NS',
    'endurance technologies ltd': 'ENDURANCE.NS',
    'engineers india ltd': 'ENGINERSIN.NS',
    'equitas small finance bank ltd': 'EQUITASBNK.NS',
    'eris lifesciences ltd': 'ERIS.NS',
    'escorts kubota ltd': 'ESCORTS.NS',
    'exide industries ltd': 'EXIDEIND.NS',
    'fdc ltd': 'FDC.NS',
    'fsn e commerce ventures ltd': 'NYKAA.NS',
    'federal bank ltd': 'FEDERALBNK.NS',
    'fertilisers and chemicals travancore ltd': 'FACT.NS',
    'fine organic industries ltd': 'FINEORG.NS',
    'finolex cables ltd': 'FINCABLES.NS',
    'finolex industries ltd': 'FINPIPE.NS',
    'firstsource solutions ltd': 'FSL.NS',
    'five star business finance ltd': 'FIVESTAR.NS',
    'fortis healthcare ltd': 'FORTIS.NS',
    'gail india ltd': 'GAIL.NS',
    'gmm pfaudler ltd': 'GMMPFAUDLR.NS',
    'gmr airports infrastructure ltd': 'GMRINFRASTRUCT.NS',
    'garden reach shipbuilders engineers ltd': 'GRSE.NS',
    'general insurance corporation of india': 'GICRE.NS',
    'gillette india ltd': 'GILLETTE.NS',
    'gland pharma ltd': 'GLAND.NS',
    'glaxosmithkline pharmaceuticals ltd': 'GLAXO.NS',
    'glenmark life sciences ltd rebranded as alivus': 'ALIVUS.NS',
    'glenmark pharmaceuticals ltd': 'GLENMARK.NS',
    'global health ltd': 'MEDANTA.NS',
    'godawari power ispat ltd': 'GPIL.NS',
    'godfrey phillips india ltd': 'GODFRYPHLP.NS',
    'godrej consumer products ltd': 'GODREJCP.NS',
    'godrej industries ltd': 'GODREJIND.NS',
    'godrej properties ltd': 'GODREJPROP.NS',
    'granules india ltd': 'GRANULES.NS',
    'graphite india ltd': 'GRAPHITE.NS',
    'grasim industries ltd': 'GRASIM.NS',
    'great eastern shipping co ltd': 'GESHIP.NS',
    'grindwell norton ltd': 'GRINDWELL.NS',
    'gujarat ambuja exports ltd': 'GAEL.NS',
    'gujarat fluorochemicals ltd': 'FLUOROCHEM.NS',
    'gujarat gas ltd': 'GUJGASLTD.NS',
    'gujarat mineral development corporation ltd': 'GMDCLTD.NS',
    'gujarat narmada valley fertilizers and chemicals ltd': 'GNFC.NS',
    'gujarat pipavav port ltd': 'GPPL.NS',
    'gujarat state fertilizers chemicals ltd': 'GSFC.NS',
    'gujarat state petronet ltd': 'GSPL.NS',
    'h e g ltd': 'HEG.NS',
    'hbl power systems ltd': 'HBLENGINE.NS',
    'hcl technologies ltd': 'HCLTECH.NS',
    'hdfc asset management company ltd': 'HDFCAMC.NS',
    'hdfc bank ltd': 'HDFCBANK.NS',
    'hdfc life insurance company ltd': 'HDFCLIFE.NS',
    'hfcl ltd': 'HFCL.NS',
    'happiest minds technologies ltd': 'HAPPSTMNDS.NS',
    'happy forgings ltd': 'HAPPYFORGE.NS',
    'havells india ltd': 'HAVELLS.NS',
    'hero motocorp ltd': 'HEROMOTOCO.NS',
    'himadri speciality chemical ltd': 'HSCL.NS',
    'hindalco industries ltd': 'HINDALCO.NS',
    'hindustan aeronautics ltd': 'HAL.NS',
    'hindustan copper ltd': 'HINDCOPPER.NS',
    'hindustan petroleum corporation ltd': 'HINDPETRO.NS',
    'hindustan unilever ltd': 'HINDUNILVR.NS',
    'hindustan zinc ltd': 'HINDZINC.NS',
    'hitachi energy india ltd': 'POWERINDIA.NS',
    'home first finance company india ltd': 'HOMEFIRST.NS',
    'honasa consumer ltd': 'HONASA.NS',
    'honeywell automation india ltd': 'HONAUT.NS',
    'housing urban development corporation ltd': 'HUDCO.NS',
    'icici bank ltd': 'ICICIBANK.NS',
    'icici lombard general insurance company ltd': 'ICICIGI.NS',
    'icici prudential life insurance company ltd': 'ICICIPRULI.NS',
    'icici securities ltd': 'ISEC.NS',
    'idbi bank ltd': 'IDBI.NS',
    'idfc first bank ltd': 'IDFCFIRSTB.NS',
    'ifci ltd': 'IFCI.NS',
    'iifl finance ltd': 'IIFL.NS',
    'irb infrastructure developers ltd': 'IRB.NS',
    'ircon international ltd': 'IRCON.NS',
    'itc ltd': 'ITC.NS',
    'iti ltd': 'ITI.NS',
    'india cements ltd': 'INDIACEM.NS',
    'indiamart intermesh ltd': 'INDIAMART.NS',
    'indian bank': 'INDIANB.NS',
    'indian energy exchange ltd': 'IEX.NS',
    'indian hotels co ltd': 'INDHOTEL.NS',
    'indian oil corporation ltd': 'IOC.NS',
    'indian overseas bank': 'IOB.NS',
    'indian railway catering and tourism corporation ltd': 'IRCTC.NS',
    'indian railway finance corporation ltd': 'IRFC.NS',
    'indigo paints ltd': 'INDIGOPNTS.NS',
    'indraprastha gas ltd': 'IGL.NS',
    'indus towers ltd': 'INDUSTOWER.NS',
    'indusind bank ltd': 'INDUSINDBK.NS',
    'info edge india ltd': 'NAUKRI.NS',
    'infosys ltd': 'INFY.NS',
    'inox wind ltd': 'INOXWIND.NS',
    'intellect design arena ltd': 'INTELLECT.NS',
    'interglobe aviation ltd': 'INDIGO.NS',
    'ipca laboratories ltd': 'IPCALAB.NS',
    'j b chemicals pharmaceuticals ltd': 'JBCHEPHARM.NS',
    'j k cement ltd': 'JKCEMENT.NS',
    'jbm auto ltd': 'JBMA.NS',
    'jk lakshmi cement ltd': 'JKLAKSHMI.NS',
    'jk paper ltd': 'JKPAPER.NS',
    'jm financial ltd': 'JMFINANCIL.NS',
    'jsw energy ltd': 'JSWENERGY.NS',
    'jsw infrastructure ltd': 'JSWINFRA.NS',
    'jsw steel ltd': 'JSWSTEEL.NS',
    'jai balaji industries ltd': 'JAIBALAJI.NS',
    'jammu kashmir bank ltd': 'J&KBANK.NS',
    'jindal saw ltd': 'JINDALSAW.NS',
    'jindal stainless ltd': 'JSL.NS',
    'jindal steel power ltd': 'JINDALSTEL.NS',
    'jio financial services ltd': 'JIOFIN.NS',
    'jubilant foodworks ltd': 'JUBLFOOD.NS',
    'jubilant ingrevia ltd': 'JUBLINGREA.NS',
    'jubilant pharmova ltd': 'JUBLPHARMA.NS',
    'jupiter wagons ltd': 'JWL.NS',
    'justdial ltd': 'JUSTDIAL.NS',
    'jyothy labs ltd': 'JYOTHYLAB.NS',
    'k p r mill ltd': 'KPRMILL.NS',
    'kei industries ltd': 'KEI.NS',
    'knr constructions ltd': 'KNRCON.NS',
    'kpit technologies ltd': 'KPITTECH.NS',
    'krbl ltd': 'KRBL.NS',
    'ksb ltd': 'KSB.NS',
    'kajaria ceramics ltd': 'KAJARIACER.NS',
    'kalpataru projects international ltd': 'KPIL.NS',
    'kalyan jewellers india ltd': 'KALYANKJIL.NS',
    'kansai nerolac paints ltd': 'KANSAINER.NS',
    'karur vysya bank ltd': 'KARURVYSYA.NS',
    'kaynes technology india ltd': 'KAYNES.NS',
    'kec international ltd': 'KEC.NS',
    'kfin technologies ltd': 'KFINTECH.NS',
    'kotak mahindra bank ltd': 'KOTAKBANK.NS',
    'krishna institute of medical sciences ltd': 'KIMS.NS',
    'l t finance ltd': 'LTF.NS',
    'l t technology services ltd': 'LTTS.NS',
    'lic housing finance ltd': 'LICHSGFIN.NS',
    'ltimindtree ltd': 'LTIM.NS',
    'larsen toubro ltd': 'LT.NS',
    'latent view analytics ltd': 'LATENTVIEW.NS',
    'laurus labs ltd': 'LAURUSLABS.NS',
    'laxmi organic industries ltd': 'LXCHEM.NS',
    'lemon tree hotels ltd': 'LEMONTREE.NS',
    'life insurance corporation of india': 'LICI.NS',
    'linde india ltd': 'LINDEINDIA.NS',
    'lloyds metals and energy ltd': 'LLOYDSME.NS',
    'lupin ltd': 'LUPIN.NS',
    'mmtc ltd': 'MMTC.NS',
    'mrf ltd': 'MRF.NS',
    'mtar technologies ltd': 'MTARTECH.NS',
    'macrotech developers ltd': 'LODHA.NS',
    'mahanagar gas ltd': 'MGL.NS',
    'maharashtra seamless ltd': 'MAHSEAMLES.NS',
    'mahindra mahindra financial services ltd': 'M&MFIN.NS',
    'mahindra mahindra ltd': 'M&M.NS',
    'mahindra holidays resorts india ltd': 'MHRIL.NS',
    'mahindra lifespace developers ltd': 'MAHLIFE.NS',
    'manappuram finance ltd': 'MANAPPURAM.NS',
    'mangalore refinery petrochemicals ltd': 'MRPL.NS',
    'mankind pharma ltd': 'MANKIND.NS',
    'marico ltd': 'MARICO.NS',
    'maruti suzuki india ltd': 'MARUTI.NS',
    'mastek ltd': 'MASTEK.NS',
    'max financial services ltd': 'MFSL.NS',
    'max healthcare institute ltd': 'MAXHEALTH.NS',
    'mazgaon dock shipbuilders ltd': 'MAZDOCK.NS',
    'medplus health services ltd': 'MEDPLUS.NS',
    'metro brands ltd': 'METROBRAND.NS',
    'metropolis healthcare ltd': 'METROPOLIS.NS',
    'minda corporation ltd': 'MINDACORP.NS',
    'motherson sumi wiring india ltd': 'MSUMI.NS',
    'motilal oswal financial services ltd': 'MOTILALOFS.NS',
    'mphasis ltd': 'MPHASIS.NS',
    'multi commodity exchange of india ltd': 'MCX.NS',
    'muthoot finance ltd': 'MUTHOOTFIN.NS',
    'natco pharma ltd': 'NATCOPHARM.NS',
    'nbcc india ltd': 'NBCC.NS',
    'ncc ltd': 'NCC.NS',
    'nhpc ltd': 'NHPC.NS',
    'nlc india ltd': 'NLCINDIA.NS',
    'nmdc ltd': 'NMDC.NS',
    'nmdc steel ltd': 'NSLNISP.NS',
    'ntpc ltd': 'NTPC.NS',
    'narayana hrudayalaya ltd': 'NH.NS',
    'national aluminium co ltd': 'NATIONALUM.NS',
    'navin fluorine international ltd': 'NAVINFLUOR.NS',
    'nestle india ltd': 'NESTLEIND.NS',
    'network18 media investments ltd': 'NETWORK18.NS',
    'nippon life india asset management ltd': 'NAM-INDIA.NS',
    'nuvama wealth management ltd': 'NUVAMA.NS',
    'nuvoco vistas corporation ltd': 'NUVOCO.NS',
    'oberoi realty ltd': 'OBEROIRLTY.NS',
    'oil natural gas corporation ltd': 'ONGC.NS',
    'oil india ltd': 'OIL.NS',
    'olectra greentech ltd': 'OLECTRA.NS',
    'one 97 communications ltd': 'PAYTM.NS',
    'oracle financial services software ltd': 'OFSS.NS',
    'pb fintech ltd': 'POLICYBZR.NS',
    'pcbl ltd': 'PCBL.NS',
    'pi industries ltd': 'PIIND.NS',
    'pnb housing finance ltd': 'PNBHOUSING.NS',
    'pnc infratech ltd': 'PNCINFRA.NS',
    'pvr inox ltd': 'PVRINOX.NS',
    'page industries ltd': 'PAGEIND.NS',
    'patanjali foods ltd': 'PATANJALI.NS',
    'persistent systems ltd': 'PERSISTENT.NS',
    'petronet lng ltd': 'PETRONET.NS',
    'phoenix mills ltd': 'PHOENIXLTD.NS',
    'pidilite industries ltd': 'PIDILITIND.NS',
    'piramal enterprises ltd': 'PEL.NS',
    'piramal pharma ltd': 'PPLPHARMA.NS',
    'poly medicure ltd': 'POLYMED.NS',
    'polycab india ltd': 'POLYCAB.NS',
    'poonawalla fincorp ltd': 'POONAWALLA.NS',
    'power finance corporation ltd': 'PFC.NS',
    'power grid corporation of india ltd': 'POWERGRID.NS',
    'praj industries ltd': 'PRAJIND.NS',
    'prestige estates projects ltd': 'PRESTIGE.NS',
    'prince pipes and fittings ltd': 'PRINCEPIPE.NS',
    'prism johnson ltd': 'PRSMJOHNSN.NS',
    'procter gamble hygiene health care ltd': 'PGHH.NS',
    'punjab national bank': 'PNB.NS',
    'quess corp ltd': 'QUESS.NS',
    'r r kabel ltd': 'RRKABEL.NS',
    'rbl bank ltd': 'RBLBANK.NS',
    'rec ltd': 'RECLTD.NS',
    'rhi magnesita india ltd': 'RHIM.NS',
    'rites ltd': 'RITES.NS',
    'radico khaitan ltd': 'RADICO.NS',
    'rail vikas nigam ltd': 'RVNL.NS',
    'railtel corporation of india ltd': 'RAILTEL.NS',
    'rainbow childrens medicare ltd': 'RAINBOW.NS',
    'rajesh exports ltd': 'RAJESHEXPO.NS',
    'ramkrishna forgings ltd': 'RKFORGE.NS',
    'rashtriya chemicals fertilizers ltd': 'RCF.NS',
    'ratnamani metals tubes ltd': 'RATNAMANI.NS',
    'rattanindia enterprises ltd': 'RTNINDIA.NS',
    'raymond ltd': 'RAYMOND.NS',
    'redington ltd': 'REDINGTON.NS',
    'reliance industries ltd': 'RELIANCE.NS',
    'restaurant brands asia ltd': 'RBA.NS',
    'route mobile ltd': 'ROUTE.NS',
    'sbfc finance ltd': 'SBFC.NS',
    'sbi cards and payment services ltd': 'SBICARD.NS',
    'sbi life insurance company ltd': 'SBILIFE.NS',
    'sjvn ltd': 'SJVN.NS',
    'skf india ltd': 'SKFINDIA.NS',
    'srf ltd': 'SRF.NS',
    'safari industries india ltd': 'SAFARI.NS',
    'sammaan capital ltd': 'SAMMAANCAP.NS',
    'samvardhana motherson international ltd': 'MOTHERSON.NS',
    'sanofi india ltd': 'SANOFI.NS',
    'sapphire foods india ltd': 'SAPPHIRE.NS',
    'saregama india ltd': 'SAREGAMA.NS',
    'schaeffler india ltd': 'SCHAEFFLER.NS',
    'schneider electric infrastructure ltd': 'SCHNEIDER.NS',
    'shree cement ltd': 'SHREECEM.NS',
    'shree renuka sugars ltd': 'RENUKA.NS',
    'shriram finance ltd': 'SHRIRAMFIN.NS',
    'shyam metalics and energy ltd': 'SHYAMMETL.NS',
    'siemens ltd': 'SIEMENS.NS',
    'signatureglobal india ltd': 'SIGNATURE.NS',
    'sobha ltd': 'SOBHA.NS',
    'solar industries india ltd': 'SOLARINDS.NS',
    'sona blw precision forgings ltd': 'SONACOMS.NS',
    'sonata software ltd': 'SONATSOFTW.NS',
    'star health and allied insurance company ltd': 'STARHEALTH.NS',
    'state bank of india': 'SBIN.NS',
    'steel authority of india ltd': 'SAIL.NS',
    'sterling and wilson renewable energy ltd': 'SWSOLAR.NS',
    'sterlite technologies ltd': 'STLTECH.NS',
    'sumitomo chemical india ltd': 'SUMICHEM.NS',
    'sun pharma advanced research company ltd': 'SPARC.NS',
    'sun pharmaceutical industries ltd': 'SUNPHARMA.NS',
    'sun tv network ltd': 'SUNTV.NS',
    'sundaram finance ltd': 'SUNDARMFIN.NS',
    'sundram fasteners ltd': 'SUNDRMFAST.NS',
    'sunteck realty ltd': 'SUNTECK.NS',
    'supreme industries ltd': 'SUPREMEIND.NS',
    'suven pharmaceuticals ltd': 'SUVENPHAR.NS',
    'suzlon energy ltd': 'SUZLON.NS',
    'swan energy ltd': 'SWANENERGY.NS',
    'syngene international ltd': 'SYNGENE.NS',
    'syrma sgs technology ltd': 'SYRMA.NS',
    'tbo tek ltd': 'TBOTEK.NS',
    'tvs motor company ltd': 'TVSMOTOR.NS',
    'tvs supply chain solutions ltd': 'TVSSCS.NS',
    'tamilnad mercantile bank ltd': 'TMB.NS',
    'tanla platforms ltd': 'TANLA.NS',
    'tata chemicals ltd': 'TATACHEM.NS',
    'tata communications ltd': 'TATACOMM.NS',
    'tata consultancy services ltd': 'TCS.NS',
    'tata consumer products ltd': 'TATACONSUM.NS',
    'tata elxsi ltd': 'TATAELXSI.NS',
    'tata investment corporation ltd': 'TATAINVEST.NS',
    'tata motors ltd': 'TATAMOTORS.NS',
    'tata power co ltd': 'TATAPOWER.NS',
    'tata steel ltd': 'TATASTEEL.NS',
    'tata technologies ltd': 'TATATECH.NS',
    'tata teleservices maharashtra ltd': 'TTML.NS',
    'tech mahindra ltd': 'TECHM.NS',
    'tejas networks ltd': 'TEJASNET.NS',
    'the new india assurance company ltd': 'NIACL.NS',
    'the ramco cements ltd': 'RAMCOCEM.NS',
    'thermax ltd': 'THERMAX.NS',
    'timken india ltd': 'TIMKEN.NS',
    'titagarh rail systems ltd': 'TITAGARH.NS',
    'titan company ltd': 'TITAN.NS',
    'torrent pharmaceuticals ltd': 'TORNTPHARM.NS',
    'torrent power ltd': 'TORNTPOWER.NS',
    'trent ltd': 'TRENT.NS',
    'trident ltd': 'TRIDENT.NS',
    'triveni engineering industries ltd': 'TRIVENI.NS',
    'triveni turbine ltd': 'TRITURBINE.NS',
    'tube investments of india ltd': 'TIINDIA.NS',
    'uco bank': 'UCOBANK.NS',
    'uno minda ltd': 'UNOMINDA.NS',
    'upl ltd': 'UPL.NS',
    'uti asset management company ltd': 'UTIAMC.NS',
    'ujjivan small finance bank ltd': 'UJJIVANSFB.NS',
    'ultratech cement ltd': 'ULTRACEMCO.NS',
    'union bank of india': 'UNIONBANK.NS',
    'united breweries ltd': 'UBL.NS',
    'united spirits ltd': 'UNITDSPR.NS',
    'usha martin ltd': 'USHAMART.NS',
    'v guard industries ltd': 'VGUARD.NS',
    'v i p industries ltd': 'VIPIND.NS',
    'vaibhav global ltd': 'VAIBHAVGBL.NS',
    'vardhman textiles ltd': 'VTL.NS',
    'varroc engineering ltd': 'VARROC.NS',
    'varun beverages ltd': 'VBL.NS',
    'vedant fashions ltd': 'MANYAVAR.NS',
    'vedanta ltd': 'VEDL.NS',
    'vijaya diagnostic centre ltd': 'VIJAYA.NS',
    'vodafone idea ltd': 'IDEA.NS',
    'voltas ltd': 'VOLTAS.NS',
    'welspun corp ltd': 'WELCORP.NS',
    'welspun living ltd': 'WELSPUNLIV.NS',
    'westlife foodworld ltd': 'WESTLIFE.NS',
    'whirlpool of india ltd': 'WHIRLPOOL.NS',
    'wipro ltd': 'WIPRO.NS',
    'yes bank ltd': 'YESBANK.NS',
    'zf commercial vehicle control systems india ltd': 'ZFCVINDIA.NS',
    'zee entertainment enterprises ltd': 'ZEEL.NS',
    'zensar technologies ltd': 'ZENSARTECH.NS',
    'eternal ltd': 'ETERNAL.NS',
    'zydus lifesciences ltd': 'ZYDUSLIFE.NS',
    'eclerx services ltd': 'ECLERX.NS'
}